# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

application_url = "https://proved-learn-employment-names.trycloudflare.com"
client_id = "6b5e5bbdaab27f9482fe5a0a0c69b246"
embedded = true
handle = "test-bundles-app-2"
name = "test-bundles-app"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]

redirect_urls = ["https://proved-learn-employment-names.trycloudflare.com/auth/callback", "https://proved-learn-employment-names.trycloudflare.com/auth/shopify/callback", "https://proved-learn-employment-names.trycloudflare.com/api/auth/callback"]
[pos]
embedded = false
